apiVersion: v1
kind: Secret
metadata:
  name: planning-secrets
  namespace: planning-medical
type: Opaque
stringData:
  # ⚠️  CHANGER TOUTES CES VALEURS avant de déployer !
  # Encoder en base64 : echo -n "valeur" | base64
  jwt-secret:      "CHANGEZ_MOI_SECRET_FORT_2024"
  db-root-password:"MotDePasseRoot_2024!"
  db-password:     "MotDePasseDB_2024!"
  email-user:      "votre.email@gmail.com"
  email-pass:      "votre_mot_de_passe_app"
